version: '2.4'
services:
  db_services:
    image: postgres:13
    hostname: postgresql
    container_name: postgresql_service
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: data
      POSTGRES_DB: card_services_db
    networks:
      - uat-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d card_services_db"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  card_service:
    build:
      context: .
      dockerfile: Dockerfile
    image: card_service:latest
    container_name: card_services
    depends_on:
      db_services:
        condition: service_healthy
    #restart: "on-failure"
    mem_limit: 256M
    expose:
      - "18080"
    ports:
      - "18080:18080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:18080/state/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 15s
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - uat-network

networks:
  uat-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.27.0/24